export enum EGoodsCategory {
  PANEL = "PANEL",
  INVERTOR = "INVERTOR",
  BATTERY = "BATTERY",
  FASTENER = "FASTENER",
  COMPONENT = "COMPONENT",
  CHARGE_STATION = "CHARGE_STATION",
  READY_MADE_SOLUTION = "READY_MADE_SOLUTION",
}
