services:
    client:
        build:
            target: dev
        volumes:
            - ./client:/app/
            - /app/node_modules
        restart: no

    server:
        build:
            target: dev
        volumes:
            - ./server:/app/
            - /app/node_modules
        restart: no

    db:
        restart: no

    # nginx:
    #   ports:
    #     - "${NGINX_PORT}:80"
    #   command: >
    #     sh -c "
    #     envsubst '$${PORT_SERVER}'
    #     < /etc/nginx/templates/nginx.dev.conf > /etc/nginx/nginx.conf
    #     && nginx -g 'daemon off;'
    #     "
    #   restart: no
