import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { Montserrat } from "next/font/google";
import { Suspense, use } from "react";
import "./globals.css";

import { routing } from "@/src/i18n/routing";
import MuiProvider from "@/src/providers/mui-provider";
import { UtmCaptureProvider } from "@/src/providers/utm-capture-provider";
import { notFound } from "next/navigation";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "SolarMan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = use(params);
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${montserrat.variable} antialiased`}>
        <NextIntlClientProvider>
          <MuiProvider locale={locale}>
            <Suspense fallback={null}>
              <UtmCaptureProvider />
            </Suspense>
            {children}
          </MuiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
