import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { use } from "react";
import { NextIntlClientProvider } from "next-intl";
import "./globals.css";

import MuiProvider from "@/src/providers/mui-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SolarMan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = use(params);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <MuiProvider locale={locale}>{children}</MuiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
